version: '3.8'

services:
  db:
    image: ${DB_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT_HOST}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres18-data:/var/lib/postgresql/data/pgdata
    networks:
      - pg18-network

  odoo:
    build: .
    image: ${ODOO_IMAGE}
    container_name: ${ODOO_CONTAINER_NAME}
    depends_on:
      - db
    ports:
      - "${ODOO_PORT_HOST}:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=${DB_HOST}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}

      # --- KONFIGURASI INTEGRASI SIGNOZ (OPENTELEMETRY) ---
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - pg18-network
    command: opentelemetry-instrument odoo

volumes:
  postgres18-data:

networks:
  pg18-network:
    name: pg18-network
    driver: bridge
